#!/bin/bash
set -euo pipefail

rand() {
  openssl rand -base64 12
}

argonhash() {
  echo -n $1 | argon2 $(rand) -id -e -t 3 -m 16 -p 8 -l 16
}

if [[ $# -ne 2 ]]; then
  echo "usage: $0 [gid] [starting uid]"
  exit 1
fi

gid=$1
uid=$2

if [[ $gid -le 0 || $uid -le 0 ]]; then
  echo "usage: $0 [gid] [starting uid]"
  exit 1
fi

echo '-- PLEASE REVIEW THE QUERY BEFORE EXECUTING IT'
echo 'begin;'
echo
echo 'with added_user as ('
echo '  insert into users (username, password_digest, name, uid, shell, preferred_language) values'

IFS=$'\n'
comma=' '
while read -r username; do
  pw="$(rand)"
  pwhash="$(argonhash $pw)"
  echo "--  $username $pw"
  echo "  $comma ('$username', '$pwhash', '$username', '$uid', '/bin/bash', 'ko')"
  uid=$(( uid + 1 ))
  comma=','
done

echo '  returning idx'
echo ')'
echo 'insert into user_memberships (user_idx, group_idx)'
echo "  select idx, $gid from added_user;"
echo
echo 'commit;'
echo '-- PLEASE REVIEW THE QUERY BEFORE EXECUTING IT'
